### ISSUE TITLE
/git/log produces error

### ISSUE THREAD

**Issue by seebi** [AKSW/QuitStore#1]
/git/log produces this error for me:

```
builtins.AttributeError
AttributeError: 'MemoryStore' object has no attribute 'getcommits'
```

**Comment by white-gecko** [comment]
This works for me. How does your repository look like?

**Comment by splattater** [comment]
I fixed this with https://github.com/AKSW/QuitStore/commit/e98cf7ed80577a6efd0572cec57f6b8edddb44f5
