### ISSUE TITLE
Commit on other branches than master will fail

### ISSUE THREAD

**Issue by splattater** [AKSW/QuitStore#108]
After an update on a second branch (develop) quit will fail with
> quit.modules.endpoint - ERROR - failed to create commit: current tip is not the first parent

This is caused by argument "ref" defaulting to "HEAD" and not being set/changed when switching the branch in the GUI.

**Comment by splattater** [comment]
@white-gecko I guess you solved this issue this week?

**Comment by white-gecko** [comment]
Probably this is fixed in #188
