### ISSUE TITLE
QuitStore will serialize non absolute URIs to n-quads

### ISSUE THREAD

**Issue by splattater** [AKSW/QuitStore#131]
Query:

`INSERT DATA 
  { 
    GRAPH <urn:graph> 
    {
      <test> <urn:pred>  'a literal' .
    }
  }`

will be added to the corresponding file as follow:
`<test> <urn:pred>  'a literal'  <urn:graph>  .`

This line won't be parsed again by QuitStore (e.g. new instance) since <test> 

> URI 'test' is not absolute (rapper error message)

**Comment by splattater** [comment]
This issue was possibule due to missing BASE namespace. #133 will fix this.

**Comment by white-gecko** [comment]
Fixed by #133
