### ISSUE TITLE
Support query parsing for multiple queries in querystring

### ISSUE THREAD

**Issue by splattater** [AKSW/QuitStore#142]
When receiving querystrings with multiple queries (sperated by ';') the checks for BASE, default-graph-uri and named-graph-uri have to be made for each query.

**Comment by white-gecko** [comment]
@splattater Is this fixed with #121 ? Can you please check this and if it is fixed, please close this issue.

**Comment by splattater** [comment]
QueryParser checks this for each query and SPARQL Protocol spec is implemented.
