### ISSUE TITLE
Support JSON-LD as sparql response format

### ISSUE THREAD

**Issue by rmeissn** [AKSW/QuitStore#209]
It would be very handy to have JSON-LD as a sparql response format (e.g. for CONSTRUCT or DESCRIBE queries), using the `@context` notation. By having this feature I wouldn't need to implement a JSON-LD converter on my own in a preceding microservice. Maybe RDFlib supports this out of the box?!

**Comment by rmeissn** [comment]
Tip: jsonld nodejs library is able to transform from plain RDF to json-ld

**Comment by white-gecko** [comment]
Is there also support for jsonld in rdflib for Python or any other Python lib?

**Comment by white-gecko** [comment]
https://github.com/RDFLib/rdflib-jsonld

**Comment by white-gecko** [comment]
Clossed by #225. 1a81c330be0b352787bf28fbe3f11bdbc84422b1
