### ISSUE TITLE
Delete query seems broken

### ISSUE THREAD

**Issue by rmeissn** [AKSW/QuitStore#220]
Executing a delete query results in response with status code 200, but all data is still present in the store, even though the git log shows that the delete query has been recorded/executed. I tried the following queries (my graph is `http://localhost:3000/data`):

```sparql
DELETE { ?s ?p ?o } WHERE { 
  GRAPH ?graph {
    ?s ?p ?o .
  }
}

DELETE { ?s ?p ?o . } WHERE { 
  GRAPH ?graph {
    ?s ?p ?o .
  }
}


DELETE { ?s ?p ?o } WHERE { 
  GRAPH <http://localhost:3000/data> {
    ?s ?p ?o .
  }
}


DELETE { ?s ?p ?o . } WHERE { 
  GRAPH <http://localhost:3000/data> {
    ?s ?p ?o .
  }
}
```

According to the example at https://www.w3.org/TR/sparql11-update/#def_datasetPattern this should work.

**Comment by rmeissn** [comment]
This is a working query for delete:
```sparql
DELETE WHERE {
  GRAPH <http://localhost:3000/data> {
    ?s ?p ?o.
  }
}
```
I still consider the initial issue description as a bug.

**Comment by white-gecko** [comment]
In the examples you have to specify the GRAPH in the DELETE part as well.

e.g.

DELETE {   GRAPH <http://localhost:3000/data> { ?s ?p ?o . } } WHERE { 
  GRAPH <http://localhost:3000/data> {
    ?s ?p ?o .
  }
}

**Comment by rmeissn** [comment]
That's a point ^^ Many thanks!
