### ISSUE TITLE
Dependency on rdflib is not stable

### ISSUE THREAD

**Issue by BonaBeavis** [AKSW/QuitStore#278]
API is not guaranteed  to be stable.
```
'rdflib [sparql] >=4.2.2',
```

**Comment by white-gecko** [comment]
Actually I have changed it to the current master now to always test against the latest rdflib

    git+https://github.com/RDFLib/rdflib@master#egg=rdflib

Is this ok for you, what would you suggest?

**Comment by BonaBeavis** [comment]
I think it is always better to specify all dependencies as specific as possible for releases, this makes debugging easier.
When all dependecies are specific it would enough to know quitstore version or commit.
When quitstore depends on rdflibs current master, the same quitstore version could show different behavior depending on when it was installed and what commit of rdflib was current at that time.

**Comment by white-gecko** [comment]
Done with poetry #292 .
Now we have `poetry.lock` that pins, the current versions and `pyproject.toml` with the generic dependencies.
