### ISSUE TITLE
Server context path not configurable

### ISSUE THREAD

**Issue by nucknorris** [AKSW/QuitStore#67]
In order to deploy the QuitStore webapp to a different path than root (`http://localhost:80/myAwesomePath/` instead of just `http://localhost:80/`) there needs to be a config parameter that makes this path configurable.

Right now, if I deploy QuitStore on a different path, all links will still resolve to the root url (e.g. `/commits` still points at `http://localhost:80/commits` instead of `http://localhost:80/myAwesomePath/commits`).

This is how Spring [handles context paths](https://howtodoinjava.com/spring/spring-boot/change-application-root-context-path/) in the config: 

```
server.contextPath=/myAwesomePath
```

Also, this parameter should be rewritable by environment variables, in order to configure the path externally, e.g. via docker-compose:

```
quitstore:
    image: aksw/quitstore
    environment:
      - "SERVER_CONTEXTPATH=/myAwesomePath"
``` 

Again, [this](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) is how Spring does the externalized configuration. This could be used as a good "best practice".

**Comment by white-gecko** [comment]
This could be possible with `APPLICATION_ROOT` as documented here: http://flask.pocoo.org/docs/0.12/config/#builtin-configuration-values
