### ISSUE TITLE
Handling for files using the same blob

### ISSUE THREAD

**Issue by Kyrosh** [AKSW/QuitStore#78]
The System can't handle instance states where multiple files have the same blob.
Only one file will be associated with the cached blob, therefore the cache misses and the file is recreated during commit.
The problem can be recreated by creating a commit with 2 empty files to a repository.

**Comment by white-gecko** [comment]
Is this fixed by #86 ? @splattater

**Comment by splattater** [comment]
I think so, but I will add tests.

**Comment by Kyrosh** [comment]
I had time to look into this as well yesterday. The problem for the test created in #83 was a bug fixed in commit e5defec298. The files were distinquished correctly, but writing to one ohne changed the content of the file not the graph, since the InMemoryGraphAggragation created a new MemoryStore instead of using the cached one (from parsing during instance). Problem was a Graph with no Statements (or len() of 0) will be bool casted to false so 'return existing or create' creates a new graph.
Therefore, if not happened you should keep the test from #83.

**Comment by splattater** [comment]
Thanks @Kyrosh. The test from #83 was splitted into several smaller ones, so we can close this issue.
